global:
  resolve_timeout: 2m
route:
  receiver: webhook
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 2m
  group_by: [alertname]
  routes:
  - receiver: webhook
    group_wait: 10s
receivers:
- name: webhook
  webhook_configs:
  - url: http://10.98.2.200:18060/dingtalk/webhook1/send  
    send_resolved: true
